### ISSUE TITLE
Evaluate excessively long sequence pair[QUESTION]

### ISSUE THREAD

**Issue by minghao-wu** [Unbabel/COMET#105]
### Before asking: 
1. Search for similar [issues](https://github.com/Unbabel/COMET/issues).   
3. Search the [docs](https://unbabel.github.io/COMET/html/index.html).    

I briefly read though the source code and didn't get the answer.

#### What is your question?
I attempted to apply COMET to some excessively long document pairs (more than 3000 words for both source and target sequence). I didn't get any error report when doing so. How does COMET process the excessively long sequence?

#### What's your environment?

 - OS: Linux
 - Packaging: pip
 - Version: 1.1.3

**Comment by ricardorei** [comment]
Hi @minghao-wu, COMET truncates the sentence for very long sentences. Hugging face tokenizer already does that for you if you activate truncate=True. You can check the [code here](https://github.com/Unbabel/COMET/blob/master/comet/encoders/base.py#L235)

Also, since we are using a _triplet encoder_ architecture this means that both source, MT and reference have an equal capacity of 512 tokens (1536 tokens in total).

In my experience with typical MT testsets this is enough. What is your use case exactly?

**Comment by minghao-wu** [comment]
Hi @ricardorei ,

Thank you for your answer. 

Yes, 512 is typically long enough for a single sentence. However, I am working on DocNMT and trying to use COMET as a document-level measure by concatenating all the source sentences, references and hypotheses within the same document. For example, one of the common benchmark dataset in DocNMT is [IWSLT2017 En-De](https://github.com/sameenmaruf/selective-attn/tree/master/data/IWSLT2017). The document length in the test set is typically longer than 1000 words. Do you have any suggestions for this situation?

**Comment by ricardorei** [comment]
You can take a look into [this work](https://github.com/amazon-science/doc-mt-metrics)

They extended COMET and other metrics to take into account context.

You still need to score each individual segment within the document but, for each segment, the score will be computed using the previous sentences and more context sensitive.

I want to integrate that into the next release of COMET but for now I think you should take a look at their work.

**Comment by ricardorei** [comment]
You can look at their paper here: [Embarrassingly Easy Document-Level MT Metrics: How to Convert Any Pretrained Metric Into a Document-Level Metric](https://statmt.org/wmt22/pdf/2022.wmt-1.6.pdf)

**Comment by minghao-wu** [comment]
Thank you for your suggestion. I will have a look.

**Comment by mtresearcher** [comment]
@ricardorei are you planning to add document level context in COMET sometime soon already?

**Comment by seeledu** [comment]
same question
