### ISSUE TITLE
[QUESTION] Is WMT data prior to WMT17 unseen?

### ISSUE THREAD

**Issue by emjotde** [Unbabel/COMET#106]
Hi again,
just to confirm, is it safe to assume that WMT test sets (or metrics shared task data) prior to WMT17, i.e. WMT08 to WMT16 are unseen to the COMET models?

Asking for evaluation purposes.
Thanks,
Marcin

**Comment by ricardorei** [comment]
Yes, WMT08 to WMT16 was never seen by any COMET models. 

WMT 21 and WMT 22 are also great datasets that have never been used to train any COMET model.

**Comment by emjotde** [comment]
Thanks!
