### ISSUE TITLE
[QUESTION] Load the model from path

### ISSUE THREAD

**Issue by ymoslem** [Unbabel/COMET#107]
Hello!

I downloaded `wmt20-comet-da` to Google Drive. I am trying to use it in Google Colab, which is perfectly connected to Google Drive. However, every time I run the code, the model is downloaded again. I am using the lines below. Is there a way to force COMET to use the model from the path rather than re-downloading it? Maybe there are other downloads? Thanks!

```
model_path = "/content/drive/MyDrive/models/wmt20-comet-da/checkpoints/model.ckpt"
model = load_from_checkpoint(model_path)
```

**Comment by ricardorei** [comment]
hmmm thats strange because the load_from_checkpoint function does not perform any download. Can you provide more information? for example a snipped of the script?

**Comment by ymoslem** [comment]
Thanks, Ricardo!

Here is the whole script that I use:
```
# Calculate COMET
df = pd.DataFrame({"src":source_sentences, "mt":translations, "ref":references})
data = df.to_dict('records')
model_path = "/content/drive/MyDrive/models/wmt20-comet-da/checkpoints/model.ckpt"
model = load_from_checkpoint(model_path)
seg_scores, sys_score = model.predict(data, batch_size=128, gpus=1)
print("COMET:", round(sys_score*100, 2))
```

Here is a screenshot of what I see.
<img width="1149" src="https://user-images.githubusercontent.com/48152713/210431295-3ed56547-7a3c-4b4c-bb47-39149ff12539.png">

I think it does not download `wmt20-comet-da`, but it downloads that 2.24GB every time, and I am not sure what it is. Thanks!

**Comment by avaz** [comment]
From my experience what the `load_from_checkpoint` downloads extra is the `models--xlm-roberta-large`. You can download it yourself and save alongside the `wmt20-comet-da` model and set the environment variable `TRANSFORMERS_CACHE` to point to where the `models--xlm-roberta-large` is. To will avoid the download. 
I'm using comet version `1.1.3`.

**Comment by ricardorei** [comment]
Yep exactly, The downloads you are observing are the hugging face XLM-R weights. You can also cache those weights to avoid download them multiple times.

**Comment by ymoslem** [comment]
Thanks, @avaz and @ricardorei! This worked.

First, download XLM-RoBERTa.
```python
from transformers import AutoModelForMaskedLM 
model = AutoModelForMaskedLM.from_pretrained("xlm-roberta-large", cache_dir="/content/drive/MyDrive/models/")
```

Then, set the cache folder for Transformers:
```python
import os
os.environ['TRANSFORMERS_CACHE'] = "/content/drive/MyDrive/models/"
```
OR
```
export TRANSFORMERS_CACHE="/content/drive/MyDrive/models/"
```
Finally, install COMET
```
pip3 install unbabel-comet -q
```
