### ISSUE TITLE
Tag v1.1.3

### ISSUE THREAD

**Issue by BramVanroy** [Unbabel/COMET#108]
I just noticed that while 1.1.3 is the latest version on [PyPi](https://pypi.org/project/unbabel-comet/#history), it is not tagged on GitHub [releases](https://github.com/Unbabel/COMET/releases)/[tags](https://github.com/Unbabel/COMET/tags). Just for transparency, it might be useful to tag that release here as well.

**Comment by ricardorei** [comment]
You are right. The changes for v1.1.3 are just minor bumps but we should add it to tags.

Thanks for the suggestion

**Comment by ricardorei** [comment]
Done
