### ISSUE TITLE
wmt22-cometkiwi-da is not available for download.

### ISSUE THREAD

**Issue by mabdelrehim** [Unbabel/COMET#112]
## 🐛 Bug

The recently released wmt22-cometkiwi-da model is no longer available from the download link.

### To Reproduce 

installation from source release tag 1.2.0 (pre-release version)

```python
from comet import download_model, load_from_checkpoint
comet_model_path = download_model("wmt22-cometkiwi-da")
model = load_from_checkpoint(comet_model_path)
```

output
```
File /home/user/COMET/comet/download_utils.py:175, in download_file_maybe_extract(url, directory, filename, extension, check_files)
    173 # Download
    174 with tqdm(unit="B", unit_scale=True, miniters=1, desc=filename) as t:
--> 175     urllib.request.urlretrieve(url, filename=filepath, reporthook=_reporthook(t))
    177 _maybe_extract(
    178     compressed_filename=filepath, directory=directory, extension=extension
    179 )
    181 if not _check_download(*check_files):
...
File /home/user/conda/envs/comet/lib/python3.10/urllib/request.py:643, in HTTPDefaultErrorHandler.http_error_default(self, req, fp, code, msg, hdrs)
    642 def http_error_default(self, req, fp, code, msg, hdrs):
--> 643     raise HTTPError(req.full_url, code, msg, hdrs, fp)

HTTPError: HTTP Error 403: Forbidden
```

**Comment by ricardorei** [comment]
Hi @mabdelrehim, we are currently working on a new release and while we figure out new model licenses that model was made private.

Hopefully we will have some news soon.

**Comment by emjotde** [comment]
If I have a version cached from before, would you advise against using it? If yes, can you elaborate a bit?

**Comment by ricardorei** [comment]
@emjotde you can keep using it. Just respect its CC-BY-NC-SA License.

**Comment by emjotde** [comment]
Thanks, understood.

**Comment by zwhe99** [comment]
> Hi @mabdelrehim, we are currently working on a new release and while we figure out model licenses and access that model was made private.
> 
> Hopefully we will have some news soon.
@ricardorei Hi~  Any progress on opening wmt22-cometkiwi-da?

**Comment by ricardorei** [comment]
yes scores will be consistent but there in no progress on releasing the model.

**Comment by NiBin90** [comment]
> If I have a version cached from before, would you advise against using it? If yes, can you elaborate a bit?

@zwhe99 Hi, will you send a copy of wmt22-cometkiwi-da to me, thx. Email: nibin.alpha@gmail.com

**Comment by cepin19** [comment]
> > Hi @mabdelrehim, we are currently working on a new release and while we figure out model licenses and access that model was made private.
> > Hopefully we will have some news soon.
> 
> @ricardorei Hi~ Any progress on opening wmt22-cometkiwi-da? If I use a cached version of wmt22-cometkiwi-da, will its output scores be consistent with the version you will release later?

Hello, do you still have a copy of the model? Would it be possible to share it with me? I'd like to do some experiments for WMT to compare with other metrics.

**Comment by ricardorei** [comment]
I just made the model public. You can download it from Hugging Face

**Comment by ricardorei** [comment]
Link for the model: [https://huggingface.co/Unbabel/wmt22-cometkiwi-da](https://huggingface.co/Unbabel/wmt22-cometkiwi-da)

You can also use it through normal API but you have to log-in into HF first. Then you can just call `Unbabel/wmt22-cometkiwi-da`
