### ISSUE TITLE
[QUESTION] default model is not update?

### ISSUE THREAD

**Issue by minghao-wu** [Unbabel/COMET#118]
### Before asking: 
1. Search for similar [issues](https://github.com/Unbabel/COMET/issues).   
3. Search the [docs](https://unbabel.github.io/COMET/html/index.html).    

#### What is your question?

I am trying to evaluate my translation outputs with `wmt22-comet-da`, the new default model. I tried to re-install the package using `pip install -I unbabel-comet` and install the package locally. I also tried to manually specicify the model with the flag `--model Unbabel/wmt22-comet-da`, But I always receive the following error:
```
comet-score: error: Unbabel/wmt22-comet-da is not a valid checkpoint path or model choice. Choose from dict_keys(['emnlp20-comet-rank', 'wmt20-comet-da', 'wmt20-comet-qe-da', 'wmt20-comet-qe-da-v2', 'wmt21-comet-da', 'wmt21-comet-mqm', 'wmt21-cometinho-mqm', 'wmt21-cometinho-da', 'wmt21-comet-qe-mqm', 'wmt21-comet-qe-da', 'eamt22-cometinho-da', 'eamt22-prune-comet-da'])
```

#### What's your environment?

 - OS: [e.g. iOS, Linux, Win]
 - Packaging [e.g. pip, conda]
 - Version [e.g. 0.5.2.1]

**Comment by ricardorei** [comment]
Hi @minghao-wu  

I just tested the code on master and everything seems to work. You sure everything was well installed locally?

We have not updated Pip yet. Ill do it this week. But if you install it from source it should work well.

**Comment by minghao-wu** [comment]
Hi @ricardorei ,

Thank you for your quick reply. Maybe there is some underlying problem on my server. No worries, I will wait for the pip update. Thanks.
