### ISSUE TITLE
Version 2.0

### ISSUE THREAD

**Issue by david-macleod** [Unbabel/COMET#119]
Hi

In the current PyPi package there a dependency on torch < 2, but this does not appear to be present on master. Do you either have a timeline on when latest might be on PyPi? If not, do you know if running comet v1.13 against torch 2.0 can expect bad things to happen?

Many thanks!

**Comment by ricardorei** [comment]
Hi @david-macleod 

torch 2.0 is still in beta, it' not even available on pypi. The latest version in pypi is 1.13.1

To be fair I have never tested 2.0 but if there is 100% backwards compatibility it will work well with COMET. The release of the new version to pypi will happen very soon. Frankly it has been delayed by several weeks already

**Comment by david-macleod** [comment]
Thanks, now that torch 2.0 is out we are still not able to bump due to unbabel-comet (even when using `unbabel-comet==2.0`). Could you point me to where the `Collecting torch<2.0.0,>=1.6.0` limitation is coming from?
