### ISSUE TITLE
Models not accessible

### ISSUE THREAD

**Issue by ankunchu** [Unbabel/COMET#121]
## 🐛 Bug

I get the following error when running COMET from the commandline:

```
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/api/models/wmt20-comet-qe-da/revision/main
```
Same behavior with other models as well. This was working perfectly till a couple of days back.

### To Reproduce 

```
model='wmt22-comet-qe-da'
ngpus=2
srcfname="src"
reffname="ref"
hypfname="hyp"
jsonfname=$hypfname.json


comet-score -s $srcfname \
       -t $hypfname \
       --to_json $jsonfname \
       --model $model \
       --gpus $ngpus \
       --quiet 
```

### Environment
OS: [ Linux ]
Packaging [ pip ]
Version [2.0.0]

**Comment by ricardorei** [comment]
because models are now hosted on hugging face you must specify the organisation also.

This should fix it:
```
model='Unbabel/wmt20-comet-qe-da'
ngpus=2
srcfname="src"
reffname="ref"
hypfname="hyp"
jsonfname=$hypfname.json


comet-score -s $srcfname \
       -t $hypfname \
       --to_json $jsonfname \
       --model $model \
       --gpus $ngpus \
       --quiet 
```

The above command will download and cache [Unbabel/wmt20-comet-qe-da](https://huggingface.co/Unbabel/wmt20-comet-qe-da)
