### ISSUE TITLE
Comet QE asks for the reference

### ISSUE THREAD

**Issue by kocmitom** [Unbabel/COMET#13]
Using the comet score with QE model (wmt-large-qe-estimator-1719) through the command line asks for a reference, even when it shouldn't be used in the calculation (if I am not mistaken)

**Comment by ricardorei** [comment]
You are right. Using the command line references are mandatory. Yet COMET-QE does not use them.. you can pass whatever you want. 

Using python you dont even need the references:

```python
from comet.models import download_model
model = download_model("wmt-large-qe-estimator-1719")
data = [{
        "src": "Dem Feuer konnte Einhalt geboten werden",
        "mt": "The fire could be stopped",
}, {
        "src": "Schulen und Kindergärten wurden eröffnet.",
        "mt": "Schools and kindergartens were open"
}]
model.predict(data, cuda=True, show_progress=True)
```
> ([{'src': 'Dem Feuer konnte Einhalt geboten werden', 'mt': 'The fire could be stopped', 'predicted_score': 0.008310817182064056}, {'src': 'Schulen und Kindergärten wurden eröffnet.', 'mt': 'Schools and kindergartens were open', 'predicted_score': 0.7012745141983032}], [0.008310817182064056, 0.7012745141983032])
