### ISSUE TITLE
How to reproduce Unbabel/wmt22-comet-da model

### ISSUE THREAD

**Issue by babangain** [Unbabel/COMET#138]
I want to train the model Unbabel/wmt22-comet-da model from scratch.
It will be very helpful for me if someone provides the list of datasets, pre-processing steps, and hyperparameters.

**Comment by ricardorei** [comment]
Btw the seed used is 91 if I am not mistaken... `comet-train --cfg YOUR_CONFIGS.yaml --seed_everything 91`
