### ISSUE TITLE
whar aspects of language gets considered while evaluating the tranlsation by COMET. as far as I am aware of MQM metric sare covered in it. Interested to know other terminolofy/features of language gets in COMET.

### ISSUE THREAD

**Issue by suyogkute** [Unbabel/COMET#174]
### Before asking: 
1. Search for similar [issues](https://github.com/Unbabel/COMET/issues).   
3. Search the [docs](https://unbabel.github.io/COMET/html/index.html).    

#### What's your environment?

 - OS: [e.g. iOS, Linux, Win]
 - Packaging [e.g. pip, conda]
 - Version [e.g. 0.5.2.1]

**Comment by ricardorei** [comment]
duplicate of #175
