### ISSUE TITLE
[QUESTION] How to calculate corpus level COMET?

### ISSUE THREAD

**Issue by AmitMY** [Unbabel/COMET#2]
I understand COMET returns a single score for each sentence it evaluates. I was wondering if there is any way to report a corpus level metric, and what would one be? Similar to how BLEU is reported.

**Comment by ricardorei** [comment]
Hey @AmitMY to get a corpus score you just have to average the segment level scores. 

We did that for the WMT20 shared task and it works pretty well: [Unbabel’s Participation in the WMT20 Metrics Shared Task](http://www.statmt.org/wmt20/pdf/2020.wmt-1.101.pdf)

Also, the CLI score command already returns you a corpus score.

**Comment by AmitMY** [comment]
Thanks!
I am using the python API, and only getting segment level scores, but averaging them is easy enough :) 

Not closing because I think its worth adding to the README?

**Comment by AmitMY** [comment]
Also, the mean sometimes comes out negative, and the more data I have the more the mean tends towards 0.

**Comment by ricardorei** [comment]
Yes, that can happen with models trained on DA's... but the fact that the means tends towards zero only depends on the distribution of the samples you are adding.

**Comment by ricardorei** [comment]
To better interpret the final score you can check our [FAQs](https://unbabel.github.io/COMET/html/models.html#faq)
