### ISSUE TITLE
[QUESTION] Does COMET support multiple references?

### ISSUE THREAD

**Issue by zdou0830** [Unbabel/COMET#20]
Thanks for the tool! I'm wondering if COMET supports multiple references, or if we can just score each sentence with all the references and take the maximum value? Sorry if this has already been mentioned somewhere.

**Comment by ricardorei** [comment]
Hi! This is actually an open question. We did some experiments where we tried to experiment with multiple references and from our experiments, a simple average is what works best. We found that using a reliable reference is actually more important than having multiple references (if they are of lower quality)
