### ISSUE TITLE
Model download error

### ISSUE THREAD

**Issue by elbadrashiny** [Unbabel/COMET#22]
## ❓ Questions and Help

I tried to download the model using:
model = download_model("wmt-large-da-estimator-1719"

But I get the following error:

'''
AttributeError                            Traceback (most recent call last)
<ipython-input-3-46133d14a8d8> in <module>
     
----> 4 model = download_model("wmt-large-da-estimator-1719")

7 frames
/proj/tools/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py in __setattr__(self, name, value)
    817                     buffers[name] = value
    818                 else:
--> 819                     object.__setattr__(self, name, value)
    820 
    821     def __delattr__(self, name):

AttributeError: can't set attribute
'''

 - OS: [Ubuntu 18.04]
 - Packaging [pip]
 - Version [20.2.4]

**Comment by ricardorei** [comment]
which _torch_ version and _PyTorch-lightning_ version are you using?

**Comment by ricardorei** [comment]
what happens if you install version 0.0.6?

`pip install unbabel-comet==0.0.6`

**Comment by elbadrashiny** [comment]
pytorch version: 1.6.0
PyTorch-lightning version: 1.3.0

I managed to run it by commenting lines 133 to 136 in comet/models/model_base.py and replacing them with this:
for key in hparams.keys():
            self.hparams[key]=hparams[key]

**Comment by ricardorei** [comment]
I think this is related to a breaking change between Pytorch Lightning 1.2.* and 1.3.0. The requirement should be `pytorch-lightning = "<1.3"` and not `pytorch-lightning = "<=1.3"`.

If you still want, you can `pip install pytorch-lightning==1.2.8` to solve that issue

**Comment by elbadrashiny** [comment]
I see. Thank you for that!
