### ISSUE TITLE
Runtime error on Apple Silicon

### ISSUE THREAD

**Issue by SCAuFish** [Unbabel/COMET#235]
## 🐛 Bug
After installation and set-up on Apple Silicon, running the following command gives error `RuntimeError: _share_filename_: only available on CPU`
```
comet-score -s src.txt -t hyp.txt --model Unbabel/wmt22-cometkiwi-da
```

Proposed fix here: #236 

### Environment
OS: macOS
Packaging: conda
Version: lastest master branch

**Comment by ricardorei** [comment]
Thanks for the PR I am merging it and bumping the version
