### ISSUE TITLE
Refless example doesn't work with 1.0.0rc4

### ISSUE THREAD

**Issue by pks** [Unbabel/COMET#24]
### To Reproduce 

Following the README:

```
> echo -e "Dem Feuer konnte Einhalt geboten werden\nSchulen und Kindergärten wurden eröffnet." >> src.de
> echo -e "The fire could be stopped\nSchools and kindergartens were open" >> hyp.en
> comet-score -s src.de -t hyp.en --model wmt20-comet-qe-da
```

results in the following output:
```
Global seed set to 12
usage: comet-score [-h] [-s SOURCES] [-t TRANSLATIONS] [-r REFERENCES] [--batch_size BATCH_SIZE] [--gpus GPUS]
                   [--to_json TO_JSON]
                   [--model {emnlp20-comet-rank,wmt20-comet-da,wmt20-comet-qe-da,wmt21-cometinho-da}]
                   [--mc_dropout MC_DROPOUT] [--seed_everything SEED_EVERYTHING]
comet-score: error: wmt20-comet-qe-da requires -r/--references.
```

Looking at the code:
https://github.com/Unbabel/COMET/blob/61caa5a37cd4db35525cd2122d8c55423929455d/comet/cli/score.py#L79-L80
it seems that the model has to have `refless` in the name, which none of the available models have:
```
comet-score: error: argument --model: invalid choice: [...] (choose from 'emnlp20-comet-rank', 'wmt20-comet-da', 'wmt20-comet-qe-da', 'wmt21-cometinho-da')
```

### Expected behaviour
I'd hope to get a score for my hypotheses given the sources.

### Screenshots
n/a

### Environment
OS: MacOS
Packaging: pip
Version: unbabel-comet==1.0.0rc4

**Comment by ricardorei** [comment]
You are right Ill fix it. I changed the name and that test skipped. As a workaround, you can pass the source sentences "as references". They are ignored by the model

**Comment by pks** [comment]
Thanks @ricardorei! Would it make sense to also adjust `comet-compare`? Currently it throws the same error w/o references and the `-qe-da-` model:
```
usage: comet-compare [-h] [-s SOURCES] [-x SYSTEM_X] [-y SYSTEM_Y] [-r REFERENCES] [--batch_size BATCH_SIZE]
                     [--gpus GPUS] [--num_splits NUM_SPLITS] [--sample_ratio SAMPLE_RATIO] [--to_json TO_JSON]
                     [--model {emnlp20-comet-rank,wmt20-comet-da,wmt20-comet-qe-da,wmt21-cometinho-da}]
                     [--seed_everything SEED_EVERYTHING]
comet-compare: error: wmt20-comet-qe-da requires -r/--references.
```

**Comment by ricardorei** [comment]
yes, the same error has to be fixed on comet-compare
