### ISSUE TITLE
COMET not working with python 3.8

### ISSUE THREAD

**Issue by joncamgui** [Unbabel/COMET#27]
## 🐛 Bug

COMET works with python 3.6 but not with python 3.8

### Environment
OS: MacOS
Packaging: pip
Version 1.0.0rc6

### To Reproduce 

I pip installed comet on my python 3.8.12 virtual environment and then tested the example provided in the readme **Scoring with Python**

```python
seg_scores, sys_score = model.predict(data, batch_size=8, gpus=0)
```
But I get the following error:

```
/usr/local/Cellar/python@3.8/3.8.12/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py in _launch(self, process_obj)
     45         try:
     46             reduction.dump(prep_data, fp)
---> 47             reduction.dump(process_obj, fp)
     48         finally:
     49             set_spawning_popen(None)

/usr/local/Cellar/python@3.8/3.8.12/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/reduction.py in dump(obj, file, protocol)
     58 def dump(obj, file, protocol=None):
     59     '''Replacement for pickle.dump() using ForkingPickler.'''
---> 60     ForkingPickler(file, protocol).dump(obj)
     61 
     62 #

AttributeError: Can't pickle local object 'CometModel.predict.<locals>.<lambda>'
```

I tested the same code on python 3.6 and it did work, so thanks a lot :)

I expected comet to work with >=python3.5
Is there any plan to make it work for python 3.8?

Thanks again.

**Comment by ShivaliGoel** [comment]
Hi, I had the same issue. I switched to Python 3.7 and pandas==1.1.5 to make it work for me. (Installed from pip & running locally- no GPU)

**Comment by ricardorei** [comment]
I found the error. 

I believe during Inference Pytorch Lightning will create model copies and it will complain about the fact that there is a lambda function defines locally: https://github.com/Unbabel/COMET/blob/master/comet/models/base.py#L445 

After fixing that error it will complain about the local definition of PredictProgressBar.

I am just wondering why it works for some python versions and not for others.

**Comment by ricardorei** [comment]
Hi @mjpost can you test it using the pre-release version?

`pip install unbabel-comet==1.0.0rc8`

I fixed some of the problems reported on this thread already.

**Comment by joncamgui** [comment]
Thanks a lot @ricardorei . It works perfectly!

**Comment by WilliamTambellini** [comment]
Hi @ricardorei 
Any plan to make the official 1.0 available in standard 3.8 pip:
```
pip3.8 install unbabel-comet==1.0.0
ERROR: Could not find a version that satisfies the requirement unbabel-comet==1.0.0 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.6, 0.0.6.post1, 0.0.6.post2, 0.0.7, 0.1.0, 1.0.0rc1, 1.0.0rc2, 1.0.0rc3, 1.0.0rc4, 1.0.0rc5, 1.0.0rc6, 1.0.0rc7, 1.0.0rc8, 1.0.0rc9)
ERROR: No matching distribution found for unbabel-comet==1.0.0
```
Best
W.

**Comment by ricardorei** [comment]
@WilliamTambellini I release version 1.0 a few hours ago and I tested it on python 3.8. [As you can see](https://pypi.org/project/unbabel-comet/#history) your pip should return you 1.0.0 and 1.0.1 versions

**Comment by ricardorei** [comment]
have you tried to upgrade pip?

**Comment by ricardorei** [comment]
I am reopening this until its fixed.

**Comment by FayeXXX** [comment]
@AnanyaCoder 
the same error occours in my python3.7 env, have you figured it out?

**Comment by msoutopico** [comment]
I am getting the same error with Python 3.11.8:
```
Traceback (most recent call last):
  File "/home/souto/Repos/msoutopico/python-comet/code/main.py", line 2, in <module>
    from comet import download_model, load_from_checkpoint
ImportError: cannot import name 'download_model' from 'comet' (/home/souto/.cache/pypoetry/virtualenvs/python-comet-nDgw5fZj-py3.11/lib/python3.11/site-packages/comet/__init__.py)
```

**Comment by OrianeN** [comment]
> I am getting the same error with Python 3.11.8:
> 
> ```
> Traceback (most recent call last):
>   File "/home/souto/Repos/msoutopico/python-comet/code/main.py", line 2, in <module>
>     from comet import download_model, load_from_checkpoint
> ImportError: cannot import name 'download_model' from 'comet' (/home/souto/.cache/pypoetry/virtualenvs/python-comet-nDgw5fZj-py3.11/lib/python3.11/site-packages/comet/__init__.py)
> ```

I got this error 2 days ago and realized the PyPi package I had installed was https://pypi.org/project/Comet/ and not https://pypi.org/project/unbabel-comet/. Uninstalling the Comet and installing the unbabel-comet package solved it in my case, hope it does for yours as well !
