### ISSUE TITLE
certificate verify failed: unable to get local issuer certificate

### ISSUE THREAD

**Issue by ricardorei** [Unbabel/COMET#29]
## 🐛 Bug

`urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)> `

error when running `comet-score` on **python >3.7 MacOS.**

### To Reproduce 

Install python via homebrew, create a virtual environment with comet and then run `comet-score`.

### Environment

OS: macOS Mojave 10.14.6

### Additional context

It seems that, for some reason, Brew has not run the Install Certificates.command that comes in the Python3 bundle for Mac.

**Comment by too-spesher** [comment]
TOP!!!! THANK YOU !!!!!

**Comment by Mxngls** [comment]
I still have the issue. I searched through a bunch of similar Stackoverflow questions, but none of the suggested solutions seem to work. Any idea why this solution (even though the error message is exactly the same) is not working in my case?

**Comment by michalrusinowski** [comment]
@ricardorei  Big thank you!

**Comment by amotl** [comment]
We started observing this problem on GHA/macOS, when adding Python 3.11 to the test matrix. It still works on any other operating system or Python version. Your suggestion fixed the problem, @ricardorei. Thanks a stack.

<details>

- `CERTIFICATE_VERIFY_FAILED`: https://github.com/crate/crate-python/actions/runs/3152435065/jobs/5127728530#step:4:240
- Success with `install_certifi.py`: https://github.com/crate/crate-python/actions/runs/3153047916/jobs/5129043155
</details>

**Comment by PauloProCoder** [comment]
I honestly was desesperated for an answer to this problem, and no teacher in my university could help me...
Don't have any words to express how greatful I'm for this solution!
