### ISSUE TITLE
Calling xlm-roberta-large via HuggingFace

### ISSUE THREAD

**Issue by kayuksel** [Unbabel/COMET#34]
## 🚀 Feature
I would like to use this library for COMET scores but I want to host xlm-roberta-large elsewhere like HuggingFace. How we can enable in this library? Would modifying xlmr.py be enough to call the XLM model that is deployed to a remote GPU server?

### Motivation
I would like to place the computationally intensive encoder of the model on a GPU server (for faster batch-inference) that is shared by multiple COMET scorers but also maybe with other applications that may also be benefiting from xlm-roberta-large.

**Comment by ricardorei** [comment]
I am not sure I understand this. But we added Embedding Caching to COMET.

This means that after you instantiate a COMET model and that model will reuse computations for repeated batches (during inference only). Yet I think you mean something else... I think you want the "heavy" weight to be performed in a different machine and then we just reuse those embeddings? That seems over-complicated... What is your use case for this?
