### ISSUE TITLE
[QUESTION] Is comet download still a supported command? 

### ISSUE THREAD

**Issue by isabelcachola** [Unbabel/COMET#36]
#### What is your question?

Is `comet download` still a supported command? If not, what is the best way to download the data needed to reproduce the results? 

#### Code

```{bash}
$ comet download --help
=>  command not found: comet
$ comet-download --help
=>  command not found: comet-download
```

#### What have you tried?

I tried running `comet download` as specified in `data/README.md`, and I get the error `command not found: comet`. However, `comet-score` and `comet-compare` works, so I know that I did install it. I also tried `comet-download` and still get the same error. 

#### What's your environment?

 - OS: macOS Big Sur 11.5.2
 - Packaging: conda 
 - Version 4.8.3 
 - Python 3.9.7

**Comment by chanberg** [comment]
Hi @ricardorei,

Are there already any similar download links for the 2021 shared task? 
Thank you!

Cheers,
Chantal

**Comment by ricardorei** [comment]
Hi @chanberg 

This is the link for 2020 DA's:
```bash
wget https://unbabel-experimental-data-sets.s3.eu-west-1.amazonaws.com/wmt/2020-da.csv.tar.gz
```

2020 DA Relative-Ranks:
```bash
wget https://unbabel-experimental-data-sets.s3.eu-west-1.amazonaws.com/wmt/2020-daRR.csv.tar.gz
```

And for the MQM data you have it [here](https://github.com/google/wmt-mqm-human-evaluation) but I'll try to upload the exact files we used after splitting the data and creating the z-scores. I'll try to do that later today or tomorrow..

**Comment by chanberg** [comment]
@ricardorei thank you so much!

**Comment by ricardorei** [comment]
@chanberg I also prepared the WMT20 MQM annotated data.

The entire dataset with MQM sentence scores and the corresponding z-score:
```bash
wget https://unbabel-experimental-data-sets.s3.eu-west-1.amazonaws.com/wmt/2020-MQM.csv.tar.gz
```

The train split we used::
```bash
wget https://unbabel-experimental-data-sets.s3.eu-west-1.amazonaws.com/wmt/2020-MQM.train.csv.tar.gz
```

The corresponding test split:
```bash
wget https://unbabel-experimental-data-sets.s3.eu-west-1.amazonaws.com/wmt/2020-MQM.test.csv.tar.gz
```

**Comment by ricardorei** [comment]
Don't forget to cite Markus paper if you use this MQM data from 2020: 

```bash
@misc{freitag2021experts,
      title={Experts, Errors, and Context: A Large-Scale Study of Human Evaluation for Machine Translation}, 
      author={Markus Freitag and George Foster and David Grangier and Viresh Ratnakar and Qijun Tan and Wolfgang Macherey},
      year={2021},
      eprint={2104.14478},
      archivePrefix={arXiv},
      primaryClass={cs.CL}
}
```

and the WMT Metrics/News Translation tasks if you use the direct assessments!

Cheers,
Ricardo

**Comment by chanberg** [comment]
@ricardorei this is great! thank you so much!
