### ISSUE TITLE
Error when running inference on newly trained metric

### ISSUE THREAD

**Issue by chryssa-zrv** [Unbabel/COMET#37]
While inference (comet-score) using the provided metrics works well, if I try to train a new metric with comet-train and the use it to predict quality scores I get the following error:

`comet-score: error: argument --model: invalid choice: 'lightning_logs/version_19/checkpoints/epoch=1-step=129339.ckpt' (choose from 'emnlp20-comet-rank', 'wmt20-comet-da', 'wmt20-comet-qe-da', 'wmt21-cometinho-da')`

The error disappears once I comment out line 64: `choices=available_metrics.keys(),` in comet/cli/score.py

```
parser.add_argument(
        "--model",
        type=Union[str, Path_fr],
        required=False,
        default="wmt20-comet-da",
        choices=available_metrics.keys(),
        help="COMET model to be used.",
    )
```

**Comment by ricardorei** [comment]
Done!

You can now do: comet-score -s src.de -t hyp1.en hyp2.en -r ref.en --model YOUR/CHECKPOINT
