### ISSUE TITLE
Requirements conflicts

### ISSUE THREAD

**Issue by kocmitom** [Unbabel/COMET#4]
Hi,
I am using your tool in my python pipelines, but I had a problem, that your requirements are too strict and I get conflict with many tools. Could you please reinvestigate if you must specify all packages on exact version?
Additionally, are you planning to shift into transformer3? 
Thank you,
TK

**Comment by ricardorei** [comment]
Hey! Besides pytorch-transformers do you have any requirement that is giving you conflicts? 

We plan to move to pytorch-transformers soon.

**Comment by kocmitom** [comment]
I have a conflict with several libraries, however, I created a temporary solution by having a second environment. But basically, transformers 3 was the main conflict which cannot be solved by downgrading, others conflicts were only in different versions (for example you don't use the latest pandas 1.1.4). 

If the modules are not strictly reliable on given libraries, maybe could you be more relaxed with requirements? For example:
pandas==1.* instead of pandas==1.0.* 
I know there could be conflicts introduced this way, but maybe not all modules have to be set on the exact version
