### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable when calling comet-score

### ISSUE THREAD

**Issue by loic-mt** [Unbabel/COMET#43]
### To Reproduce 

Using comet 1.0.1 with Python 3.9, I get the following (using testset in /data of mt-telescope):

$ comet-score -s newstest2020-ruen.src.ru.txt -t newstest2020-ruen.OnlineA.txt -r newstest2020-ruen.ref.en.txt 
Global seed set to 12
wmt20-comet-da is already in cache.
Traceback (most recent call last):
  File ".../telescope-venv/bin/comet-score", line 8, in <module>
    sys.exit(score_command())
  File ".../telescope-venv/lib/python3.9/site-packages/comet/cli/score.py", line 180, in score_command
    model = load_from_checkpoint(model_path)
  File ".../telescope-venv/lib/python3.9/site-packages/comet/models/__init__.py", line 57, in load_from_checkpoint
    model_class = str2model[hparams["class_identifier"]]
TypeError: 'NoneType' object is not subscriptable

### Expected behaviour

Output comet score.

### Environment
OS: Linus
Packaging Pip
Version 1.0.1

**Comment by loic-mt** [comment]
If that makes a difference, this was run without gpu.

**Comment by loic-mt** [comment]
It's 1.3.5

**Comment by ricardorei** [comment]
That's the correct version. I just tested it locally using python 3.9 and everything went well... I am not able to reproduce the error. Can you send me your exact virtual env?
