### ISSUE TITLE
[QUESTION] Train my own metrics without source sentences

### ISSUE THREAD

**Issue by xu1998hz** [Unbabel/COMET#48]
Hi Ricardo, thank you so much for your previous answers.
I have a follow-up question regarding to train Comet myself without using any source sentences. 

So the input to the system will be translated sentences, reference sentences and the rating of the translations.
Is there a way to do this in the current code base? Thank you in advance.

**Comment by ricardorei** [comment]
No, the current models accept either `source` and `translation` (Quality estimation setting) or `source`, `translation` and `reference` (MT metrics setting). To support your use case you will have to change the codebase.

Do you want to create a metric that receives `translation`, `reference`, and a `score` right? I think the easiest way is to create something similar to the [referenceless.py](https://github.com/Unbabel/COMET/blob/master/comet/models/regression/referenceless.py) metric but replacing the `source` with the `reference` as text inputs. Regarding the `score` I would incorporate that input in the feed-forward on top, after the encoding of the text inputs.

**Comment by ricardorei** [comment]
tell me if you need any help.

**Comment by xu1998hz** [comment]
Thank you very much! I will go ahead and modify referenceless.py.
Btw, do you think it is possible for me to change "monitor: val_pearson" in earlystopping.yaml to some customized metrics like kendall correlation?

**Comment by ricardorei** [comment]
the WMT kendall-tau like metric based on daRR or just plain Kendall tau?

Modifying it for monitoring "plain" Kendall tau is easy although you will have to implement it. The WMT Kendall-tau based on daRR is going to give you more work ...

**Comment by ricardorei** [comment]
Our implementation uses the [regression metrics from torchmetrics](https://torchmetrics.readthedocs.io/en/latest/references/modules.html#regression-metrics). They dont have kendall-tau and thats why we only look at Pearson and Spearman... but you can extend their library and [build your custom metric](https://torchmetrics.readthedocs.io/en/latest/pages/implement.html) like kendall

**Comment by ricardorei** [comment]
I did exactly that for the WMT Kendall when building the translation ranking model: [ wmt_kendall.py](https://github.com/Unbabel/COMET/blob/master/comet/models/ranking/wmt_kendall.py)

**Comment by xu1998hz** [comment]
Cool! Thank you for your quick response. I am trying to build WMT kendall-tau. In this case, can I directly use your script wmt_kendall.py?

**Comment by ricardorei** [comment]
you can yes, but you will have to pass the score for the better and worse MT. This means that for regression metrics, during validation, you will have to load a different corpus with 4 texts (source, better MT, worse MT, reference).

**Comment by xu1998hz** [comment]
Oh I see. Thank you so much! I assumed for ranking model that I can just call your wmt kendall metric with the same corpus.

**Comment by ricardorei** [comment]
if you are using the ranking model yes. If you are using regression models you have to adapt the validation part

**Comment by xu1998hz** [comment]
Great! Thank you for all your answers again.
