### ISSUE TITLE
GPU support information into README

### ISSUE THREAD

**Issue by kocmitom** [Unbabel/COMET#5]
COMET takes 30-40 minutes to evaluate 400 sentences testset on CPU. Therefore GPU is necessary, but it took me some time before I found out there is a flag "cuda". Can you add an example with cuda parametr into README?

**Comment by ricardorei** [comment]
Thanks for the feedback. I'll add that. Actually, we will work on documentation this week. 

We will add an explanation to all CLI flags and a few results from WMT20

If you have anything else, just say and we will try to add it!
