### ISSUE TITLE
No quiet flag

### ISSUE THREAD

**Issue by erip** [Unbabel/COMET#65]
### To Reproduce 

Use `comet-score` with the `--quiet` flags described in the docs.

### Expected behaviour

Per the docs, the `--quiet` flag should suppress all output but the final score.

### Screenshots

N/A

### Environment
OS: Linux
Packaging: Pip
Version: 1.0.1

**Comment by ricardorei** [comment]
I'll check this soon and keep you updated. Thanks, @erip!

**Comment by ricardorei** [comment]
hi @erip! how are you?

I just looked into this and it seems to be working well. What do you mean by `suppress all output but the final score`?

The goal is just to suppress the segment-level scores. It still keeps the progress bar etc.

**Comment by ricardorei** [comment]
The quiet flag was added to master recently. It is not released in pip yet. 

I mean that it suppresses the other segment-level scores.

I'll probably release the new version soon. Meanwhile, that feature is only available if you install the package from source.

**Comment by erip** [comment]
Ah, understood! Thanks very much.
