### ISSUE TITLE
pip install conflict

### ISSUE THREAD

**Issue by kocmitom** [Unbabel/COMET#7]
When I tried a clean install of current COMET version via pip, I got an error that there is a conflict in versions. I managed to resolve it by manually degrading PyYAML to 3.3.*

Could you check it, please?

**Comment by kocmitom** [comment]
Maybe it will be resolved by https://github.com/Unbabel/COMET/pull/6 ... I am sorry for possibly old bug report :)

**Comment by ricardorei** [comment]
I think you are right, it's not an old bug. What python version are you using?

**Comment by kocmitom** [comment]
I am using Python 3.8.5. And I used a clean virtual environment installing only comet (I did this last Friday).

**Comment by ricardorei** [comment]
and what about the operative system? 

I had also other similar bug reports from users (see #8 ) since I updated COMET. Yet, both in my computer (Mac OS) and in a Ubuntu VM worked well. I am trying to figure out the real issue here.

**Comment by kocmitom** [comment]
We use Ubuntu 20.04.1 LTS
I can rerun it again. Basically, the problem is that "pytorch-lightning" wanted a different version of PyYAML than something else has installed. The only command I ran on a new virtual environment was "pip install unbabel-comet"
Btw. I made a typo, the PyYAML version that solved the problem was 5.3.*

**Comment by kocmitom** [comment]
Thanks for updating, I checked the installation on our machines and now it works perfectly :)

**Comment by ricardorei** [comment]
Thanks for the feedback!
I tried Poetry for the first time I hope it makes everything easier with dependencies now
