### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by mahfuzibnalam** [Unbabel/COMET#84]
### Before asking: 
1. Search for similar [issues](https://github.com/Unbabel/COMET/issues).   
3. Search the [docs](https://unbabel.github.io/COMET/html/index.html).    

#### What is your question?
1. There seems to be a huge code difference between the repository and the pip-installed version. Which pip-installed version matches the most with the current repository?

Suppose my pip-installed version needs this CLI command: "comet score -s src.de -h hyp1.en -r ref.en", where the repository says to give this CLI commad "comet-score -s src.de -t hyp1.en -r ref.en".

2. My python version is 3.6.9. Poetry does not seem to work for python < 3.7. Do you have any suggestions? 
**Installing dependencies from lock file

  SolverProblemError

  The current project's Python requirement (3.6.9) is not compatible with some of the required packages Python requirement:
    - scipy requires Python >=3.7, so it will not be satisfied for Python 3.6.9
  
  Because scipy (1.6.1) requires Python >=3.7
   and no versions of scipy match >=1.5.4,<1.6.1 || >1.6.1, scipy is forbidden.
  So, because unbabel-comet depends on scipy (>=1.5.4), version solving failed.

  at ~/research/lib/python3.6/site-packages/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│ 
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes

  • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties
    
    For scipy, a possible solution would be to set the `python` property to "<empty>"

    https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies,
    https://python-poetry.org/docs/dependency-specification/#using-environment-markers
**

3. Can you please give me the configs file to reproduce the results of the paper?
#### What's your environment?

 - OS: [Ubuntu]
 - Packaging [pip]
 - Version []

**Comment by ricardorei** [comment]
Hi @mahfuzibnalam!

unbabel-comet==1.1.2 and 1.1.1 match the code in the README. You have a constraint in python 3.6 I see.. have you tried older versions? For example 1.0.0, 1.0.1 or even 0.1.0?

You can find the corresponding READMEs [here](https://pypi.org/project/unbabel-comet/#history). The interface does not change much. The default models are also all there.

**Comment by ricardorei** [comment]
If not I can look deeper into these requirements and see if there is a simples way for you to install it.

**Comment by mahfuzibnalam** [comment]
Hello @ricardorei, 
Thank you for fast replying.
For this command: "pip install unbabel-comet==1.0.0" 
I get,
"ERROR: Could not find a version that satisfies the requirement unbabel-comet==1.0.0 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.6, 0.0.6.post1, 0.0.6.post2, 0.0.7, 0.1.0, 1.0.0rc1, 1.0.0rc2, 1.0.0rc3, 1.0.0rc4, 1.0.0rc5, 1.0.0rc6, 1.0.0rc7, 1.0.0rc8, 1.0.0rc9)
ERROR: No matching distribution found for unbabel-comet==1.0.0"

Mainly I need to work locally on this repository. Or if I can get the configs file of that specific version, that is also super helpful.
