### ISSUE TITLE
Referenceless QE metrics require reference input

### ISSUE THREAD

**Issue by zouharvi** [Unbabel/COMET#87]
## 🐛 Bug

When using comet from the `evaluate` package, it seems to require the reference also for QE metrics. There's an easy but dirty hotfix.

### To Reproduce 

```python3
comet_metric = evaluate.load("comet", config_name='wmt21-comet-qe-da')
# erorr!
comet_metric.compute(predictions=["Hallöchen"], sources=["Heyo"])
```

### More info

Passing a reference with an empty string appears to satisfy the library. I checked that the output scores are not dependent on the reference:

```python3
# {'mean_score': 0.08140071481466293, 'scores': [0.08140071481466293]}
comet_metric.compute(predictions=["Hallöchen"], sources=["Heyo"]. references=[""])
# {'mean_score': 0.08140071481466293, 'scores': [0.08140071481466293]}
comet_metric.compute(predictions=["Hallöchen"], sources=["Heyo"], references=["Howdy"])
```

**Comment by ricardorei** [comment]
Hi @zouharvi, This seems to be an issue on the `evaluate` package and not on `unbabel-comet`. I suggest you open and issue there...
