### ISSUE TITLE
comet-score [other_params] --to_json True doesn't output a json file

### ISSUE THREAD

**Issue by me-manikanta** [Unbabel/COMET#88]
## 🐛 Bug

Passing `--to_json` as `True` or `true` doesn't output any JSON file. Whereas passing any other value creates a file with that name and it has the JSON output as expected.

### To Reproduce 

- Run `comet-score` (or comet-compare) with `--to_json` as `True`
- Observe that there is no json file created

If the test is failing, please add your test cases to the issue (as a draft PR, or simply paste the code to the issue description here).

### Expected behaviour
I think the expected behaviour should be the same for any string, but if it is a boolean and is `True` we can default the output to file `output.json`. If you think this is not the expected behaviour, then changing the help text as following will avoid the confusion.

**Comment by ricardorei** [comment]
I changed the flag accept only strings. By default its the empty string and thus it does not export to a json.
