### ISSUE TITLE
Bootstrap resampling

### ISSUE THREAD

**Issue by st-vincent1** [Unbabel/COMET#95]
## 🚀 Feature
COMET could support statistical significance tests such as paired bootstrap resampling for comparing across systems.

### Motivation
Statistical significance tests, e.g. paired bootstrap resampling are encouraged as standard practice in research. Currently they are easily available for calculated metrics (BLEU, chrF etc.) via [sacrebleu](https://github.com/mjpost/sacrebleu). However, their approach does not support custom metrics.

**Comment by ricardorei** [comment]
You can use `comet-compare` command for that.

It returns the comparison of 1 or more systems using statistical significance.

**Comment by ricardorei** [comment]
Leaving here the [example from README](https://github.com/Unbabel/COMET#:~:text=When%20comparing%20multiple%20MT%20systems%20we%20encourage%20you%20to%20run%20the%20comet%2Dcompare%20command%20to%20get%20statistical%20significance%20with%20Paired%20T%2DTest%20and%20bootstrap%20resampling%20(Koehn%2C%20et%20al%202004)
